### ISSUE TITLE
Fullscreen?

### ISSUE THREAD

**Issue by Stan92** [Asymmetrik/ngx-leaflet-tutorial-plugins#2]
Hi,
It's not an issue.. but I try to integrate a fullscreen control with ngx-leaflet (https://github.com/brunob/leaflet.fullscreen) without success.
Could that be done?
Thanks

**Comment by sgrillon14** [comment]
I integrate https://github.com/brunob/leaflet.fullscreen in ngx-leaflet-tutorial-plugins.

integration of module OK but the sample is already full screen.

This issue can be close after merge of PR [#3](https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/pull/3) You can follow this PR [#3](https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/pull/3)

![image](https://user-images.githubusercontent.com/5530550/35782255-a415709c-09f5-11e8-8525-fbeec0c93f3e.png)

**Comment by Stan92** [comment]
Stéphane 
Je te remercie pour ton support 
I thank you for your support

**Comment by reblace** [comment]
This example is now available on the master branch. Thanks!
