### ISSUE TITLE
--prod flag breaks Leaflet.Fullscreen plugin

### ISSUE THREAD

**Issue by llamaonsecurity** [Asymmetrik/ngx-leaflet-tutorial-plugins#8]
Hello i have noticed that Leaflet.Fullscreen.plugin example doesn't work well with --prod flag during build or serve. It shows the map but not in the full screen mode, imho it is the problem with angular css optimization or something similar. 
Example commands:
```
ng serve --rpod  
ng build --prod
```
My angular version
```
Angular CLI: 1.6.8
Node: 9.8.0
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

```

**Comment by reblace** [comment]
Thanks for identifying this issue. If you find a solution, feel free to comment here or put in a PR to solve it. Otherwise, we'll take a look when we get a chance.

**Comment by llamaonsecurity** [comment]
Yeah i will try to resolve the issue in my spare time.

**Comment by reblace** [comment]
This looks to have been addressed in ng6. Let me know if you still see the issue.
